application: temperature
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /.*
  script: rest_api.app

libraries:
- name: jinja2
  version: "2.6"
